version: '3'
services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: extr_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
